;;; Arch applications menu for Sawfish, generated from xfce4 menu
(defvar arch-menu nil)
(setq arch-menu '(
    ("Development"
      ("Akonadi Console" (system "akonadiconsole &"))
      ("Cervisia" (system "cervisia &"))
      ("IDLE" (system "idle &"))
      ("KAppTemplate" (system "kapptemplate &"))
      ("KCachegrind" (system "kcachegrind &"))
      ("KImageMapEditor" (system "kimagemapeditor &"))
      ("KLinkStatus" (system "klinkstatus &"))
      ("Kompare" (system "kompare &"))
      ("KUIViewer" (system "kuiviewer &"))
      ("Lokalize" (system "lokalize &"))
      ("OpenJDK Monitoring & Management Console" (system "jconsole &"))
      ("OpenJDK Policy Tool" (system "policytool &"))
      ("Python" (system "urxvt -e python &"))
      ("Qt Assistant" (system "assistant &"))
      ("Qt Designer" (system "designer &"))
      ("Qt Linguist" (system "linguist &"))
      ("Umbrello" (system "umbrello &")))
    ("Editors"
      ("AA Fire" (system "urxvt -e aafire -driver slang &"))
      ("Emacs" (system "urxvt -e emacs &"))
      ("GVim" (system "gvim &"))
      ("Kate" (system "kate &"))
      ("KWrite" (system "kwrite &"))
      ("Nano" (system "urxvt -e nano &"))
      ("Vi" (system "urxvt -e vi &"))
      ("Vim" (system "urxvt -e vim &")))
    ("Education"
      ("Blinken" (system "blinken &"))
      ("Kanagram" (system "kanagram &"))
      ("KGeography" (system "kgeography &"))
      ("KHangMan" (system "khangman &"))
      ("Kiten" (system "kiten &"))
      ("KLettres" (system "klettres &"))
      ("KTouch" (system "ktouch &"))
      ("KTurtle" (system "kturtle &"))
      ("KWordQuiz" (system "kwordquiz &"))
      ("Marble" (system "marble &"))
      ("Pairs" (system "pairs &"))
      ("Parley" (system "parley &")))
    ("Games"
      ("Adventure"
        ("Sclient" (system "sclient &")))
      ("Amusement"
        ("AMOR" (system "amor &"))
        ("Potato Guy" (system "ktuberling &")))
      ("Arcade"
        ("Bomber" (system "bomber &"))
        ("Granatier" (system "granatier &"))
        ("Kapman" (system "kapman &"))
        ("KBlocks" (system "kblocks &"))
        ("KBounce" (system "kbounce &"))
        ("KBreakOut" (system "kbreakout &"))
        ("KGoldrunner" (system "kgoldrunner &"))
        ("Kolf" (system "kolf &"))
        ("Kollision" (system "kollision &"))
        ("KSnake" (system "ktron -snake &"))
        ("KSnakeDuel" (system "ktron &"))
        ("KSpaceDuel" (system "kspaceduel &"))
        ("PacMan" (system "pacman &")))
      ("Board"
        ("Bovo" (system "bovo &"))
        ("GNU Go" (system "urxvt -e gnugo &"))
        ("Kajongg" (system "kajongg &"))
        ("KBlackBox" (system "kblackbox &"))
        ("KFourInLine" (system "kfourinline &"))
        ("Kigo" (system "kigo &"))
        ("Kiriki" (system "kiriki &"))
        ("KMahjongg" (system "kmahjongg &"))
        ("KReversi" (system "kreversi &"))
        ("KSquares" (system "ksquares &"))
        ("Shisen-Sho" (system "kshisen &")))
      ("Card"
        ("KPatience" (system "kpat &"))
        ("LSkat" (system "lskat &")))
      ("Puzzle"
        ("KDiamond" (system "kdiamond &"))
        ("KSudoku" (system "ksudoku &"))
        ("Kubrick" (system "kubrick &"))
        ("Palapeli" (system "palapeli &")))
      ("Strategy"
        ("KAtomic" (system "katomic &"))
        ("Killbots" (system "killbots &"))
        ("KJumpingCube" (system "kjumpingcube &"))
        ("Klickety" (system "klickety &"))
        ("KMines" (system "kmines &"))
        ("KNetWalk" (system "knetwalk &"))
        ("Kolor Lines" (system "klines &"))
        ("Konquest" (system "konquest &"))
        ("KsirK" (system "ksirk &"))
        ("KsirK Skin Editor" (system "ksirkskineditor &"))
        ("Naval Battle" (system "kbattleship &"))
        ("SameGame" (system "klickety --KSameMode &"))))
    ("Graphics"
      ("E-book Viewer" (system "ebook-viewer &"))
      ("Gwenview" (system "gwenview &"))
      ("KColorChooser" (system "kcolorchooser &"))
      ("kgrapheditor" (system "kgrapheditor &"))
      ("kgraphviewer" (system "kgraphviewer &"))
      ("KolourPaint" (system "kolourpaint &"))
      ("KRuler" (system "kruler &"))
      ("KSnapshot" (system "ksnapshot &"))
      ("LRF Viewer" (system "lrfviewer &"))
      ("scanimage" (system "urxvt -e scanimage &"))
      ("XGlyph" (system "xglyph &")))
    ("Multimedia"
      ("ALSA mixer" (system "urxvt -e alsamixer &"))
      ("Dragon Player" (system "dragon &"))
      ("JuK" (system "juk &"))
      ("KMix" (system "kmix &"))
      ("KsCD" (system "kscd &"))
      ("SMPlayer" (system "smplayer &"))
      ("VLC media player" (system "vlc &")))
    ("Network"
      ("Akregator" (system "akregator &"))
      ("aLinkCreator" (system "alc &"))
      ("aMule" (system "amule &"))
      ("aMuleGUI" (system "amulegui &"))
      ("Avahi SSH Server Browser" (system "bssh &"))
      ("Avahi VNC Server Browser" (system "bvnc &"))
      ("Blogilo" (system "blogilo &"))
      ("Chromium" (system "chromium &"))
      ("FireFox" (system "firefox &"))
      ("FTP" (system "urxvt -e ftp &"))
      ("KGet" (system "kget &"))
      ("KMail" (system "kmail &"))
      ("KNode" (system "knode &"))
      ("Konqueror" (system "kfmclient openProfile webbrowsing &"))
      ("Kopete" (system "kopete &"))
      ("KPPP" (system "kppp &"))
      ("KRDC" (system "krdc &"))
      ("Krfb" (system "krfb &"))
      ("KTorrent" (system "ktorrent &"))
      ("Links" (system "urxvt -e links &"))
      ("Links" (system "xlinks -g &"))
      ("Mail" (system "urxvt -e mail &"))
      ("MLDonkey GUI" (system "mldonkey_gui &"))
      ("Talk" (system "urxvt -e talk &"))
      ("Telnet" (system "urxvt -e telnet &"))
      ("W3m" (system "urxvt -e w3m &"))
      ("w3m" (system "urxvt -e w3m /usr/share/doc/w3m/MANUAL.html &"))
      ("wxCas" (system "wxcas &")))
    ("Office"
      ("KAddressBook" (system "kaddressbook &"))
      ("KchmViewer" (system "kchmviewer &"))
      ("Kontact" (system "kontact &"))
      ("KOrganizer" (system "korganizer &"))
      ("KTimeTracker" (system "ktimetracker &"))
      ("KTnef" (system "ktnef &"))
      ("LibreOffice Impress" (system "libreoffice &"))
      ("Okular" (system "okular &"))
      ("PostgreSQL Database" (system "urxvt -e psql template1 &"))
      ("StarDict" (system "stardict &")))
    ("Other"
      ("Calibre" (system "calibre &"))
      ("Find Files/Folders" (system "kfind &"))
      ("Help" (system "khelpcenter &"))
      ("IBus Preferences" (system "ibus-setup &"))
      ("Lvod资源下载器" (system "/opt/lvodDownloader/start.sh &"))
      ("QT V4L2 test Utility" (system "qv4l2 &")))
    ("Science"
      ("Avogadro" (system "avogadro &"))
      ("bc" (system "urxvt -e bc &"))
      ("Cantor" (system "cantor &"))
      ("dc" (system "urxvt -e dc &"))
      ("Gnuplot" (system "urxvt -e gnuplot &"))
      ("KAlgebra" (system "kalgebra &"))
      ("KAlgebra Mobile" (system "kalgebramobile &"))
      ("Kalzium" (system "kalzium &"))
      ("KBruch" (system "kbruch &"))
      ("Kig" (system "kig &"))
      ("KmPlot" (system "kmplot &"))
      ("KStars" (system "kstars &"))
      ("Rocs" (system "rocs &"))
      ("Step" (system "step &")))
    ("Shells"
      ("Dolphin" (system "dolphin &"))
      ("GIT" (system "urxvt -e git &"))
      ("Konsole" (system "konsole &"))
      ("Rdesktop" (system "rdesktop &")))
    ("System"
      ("Settings"
        ("GNOME"
          ("Adobe Flash Player" (system "flash-player-properties &")))
        ("KDE System Settings" (system "systemsettings &"))
        ("Manage Printing" (system "xdg-open http://localhost:631/ &")))
      ("Avahi Zeroconf Browser" (system "avahi-discover &"))
      ("dconf Editor" (system "dconf-editor &"))
      ("IBus" (system "ibus-daemon --xim &"))
      ("Imlib Config" (system "imlib_config &"))
      ("KDiskFree" (system "kdf &"))
      ("KInfoCenter" (system "kinfocenter &"))
      ("KRandRTray" (system "krandrtray &"))
      ("KSystemLog" (system "ksystemlog &"))
      ("KUser" (system "kuser &"))
      ("KWalletManager" (system "kwalletmanager &"))
      ("KwikDisk" (system "kwikdisk &"))
      ("Nepomuk Backup" (system "nepomukbackup &"))
      ("Nepomuk File Indexing Controller" (system "nepomukcontroller &"))
      ("pstree" (system "urxvt -e pstree &"))
      ("pstree" (system "urxvt -e pstree.x11 &"))
      ("System Monitor" (system "ksysguard &"))
      ("Top" (system "urxvt -e top &")))
    ("Utilities"
      ("7-Zip FM" (system "7zFM &"))
      ("Akonaditray" (system "akonaditray &"))
      ("Ark" (system "ark &"))
      ("Filelight" (system "filelight &"))
      ("Info" (system "urxvt -e info &"))
      ("Jovie" (system "jovie &"))
      ("KAlarm" (system "kalarm &"))
      ("KCalc" (system "kcalc &"))
      ("KCharSelect" (system "kcharselect &"))
      ("KFileReplace" (system "kfilereplace &"))
      ("KFloppy" (system "kfloppy &"))
      ("KGpg" (system "kgpg &"))
      ("KJots" (system "kjots &"))
      ("Kleopatra" (system "kleopatra &"))
      ("Klipper" (system "klipper &"))
      ("KMag" (system "kmag &"))
      ("KMouseTool" (system "kmousetool &"))
      ("KMouth" (system "kmouth &"))
      ("KNotes" (system "knotes &"))
      ("KTeaTime" (system "kteatime &"))
      ("KTimer" (system "ktimer &"))
      ("Okteta" (system "okteta &"))
      ("SuperKaramba" (system "superkaramba &"))
      ("Sweeper" (system "sweeper &"))
      ("Xev" (system "urxvt -e xev &"))
      ("Xrefresh" (system "xrefresh &"))
      ("Xsetroot" (system "xsetroot &")))))
